In [11]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator

np.random.seed(3)

In [12]:
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        'data/handwriting_shape/train',
        target_size=(24, 24),
        batch_size=3,
        class_mode='categorical')

Found 45 images belonging to 3 classes.


In [20]:
test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        'data/handwriting_shape/test',
        target_size=(24, 24),    
        batch_size=3,
        class_mode='categorical')

Found 16 images belonging to 3 classes.


In [14]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(24,24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [15]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [16]:
hist = model.fit_generator(
            train_generator,
            steps_per_epoch=15,
            epochs=50,
            validation_data=test_generator,
            validation_steps=5)

Epoch 1/50
15/15 [==============================] - 1s 58ms/step - loss: 1.0266 - acc: 0.5556 - val_loss: 0.5252 - val_acc: 1.0000
Epoch 2/50
15/15 [==============================] - 0s 28ms/step - loss: 0.2124 - acc: 0.9556 - val_loss: 0.1478 - val_acc: 1.0000
Epoch 3/50
15/15 [==============================] - 0s 27ms/step - loss: 0.0756 - acc: 0.9778 - val_loss: 0.0252 - val_acc: 1.0000
Epoch 4/50
15/15 [==============================] - 0s 28ms/step - loss: 0.0070 - acc: 1.0000 - val_loss: 0.0117 - val_acc: 1.0000
Epoch 5/50
15/15 [==============================] - 0s 27ms/step - loss: 0.0012 - acc: 1.0000 - val_loss: 0.0081 - val_acc: 1.0000
Epoch 6/50
15/15 [==============================] - 0s 27ms/step - loss: 4.6394e-04 - acc: 1.0000 - val_loss: 0.0081 - val_acc: 1.0000
Epoch 7/50
15/15 [==============================] - 0s 28ms/step - loss: 3.5063e-04 - acc: 1.0000 - val_loss: 0.0080 - val_acc: 1.0000
Epoch 8/50
15/15 [==============================] - 0s 27ms/step - loss: 2.

In [17]:
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
acc: 100.00%


In [18]:
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

print(test_generator.class_indices)
print(output)

-- Predict --
{'circle': 0, 'rectangle': 1, 'triangle': 2}
[[1.000 0.000 0.000]
 [0.999 0.001 0.001]
 [0.000 0.000 1.000]
 [1.000 0.000 0.000]
 [0.000 1.000 0.000]
 [0.000 1.000 0.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.007 0.983 0.010]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]
 [0.000 0.000 1.000]
 [0.000 1.000 0.000]
 [0.000 0.002 0.998]
 [0.000 1.000 0.000]]
